/*Copyright (c) 2018-2019 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.auto_mglpjxobyl.multipartdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import javax.validation.Valid;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.auto_mglpjxobyl.multipartdb.Blobdata;

/**
 * Service object for domain model class {@link Blobdata}.
 */
public interface BlobdataService {

    /**
     * Creates a new Blobdata. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Blobdata if any.
     *
     * @param blobdata Details of the Blobdata to be created; value cannot be null.
     * @return The newly created Blobdata.
     */
	Blobdata create(@Valid Blobdata blobdata);


	/**
	 * Returns Blobdata by given id if exists.
	 *
	 * @param blobdataId The id of the Blobdata to get; value cannot be null.
	 * @return Blobdata associated with the given blobdataId.
     * @throws EntityNotFoundException If no Blobdata is found.
	 */
	Blobdata getById(Integer blobdataId);

    /**
	 * Find and return the Blobdata by given id if exists, returns null otherwise.
	 *
	 * @param blobdataId The id of the Blobdata to get; value cannot be null.
	 * @return Blobdata associated with the given blobdataId.
	 */
	Blobdata findById(Integer blobdataId);


	/**
	 * Updates the details of an existing Blobdata. It replaces all fields of the existing Blobdata with the given blobdata.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Blobdata if any.
     *
	 * @param blobdata The details of the Blobdata to be updated; value cannot be null.
	 * @return The updated Blobdata.
	 * @throws EntityNotFoundException if no Blobdata is found with given input.
	 */
	Blobdata update(@Valid Blobdata blobdata);

    /**
	 * Deletes an existing Blobdata with the given id.
	 *
	 * @param blobdataId The id of the Blobdata to be deleted; value cannot be null.
	 * @return The deleted Blobdata.
	 * @throws EntityNotFoundException if no Blobdata found with the given id.
	 */
	Blobdata delete(Integer blobdataId);

    /**
	 * Deletes an existing Blobdata with the given object.
	 *
	 * @param blobdata The instance of the Blobdata to be deleted; value cannot be null.
	 */
	void delete(Blobdata blobdata);

	/**
	 * Find all Blobdatas matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Blobdatas.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Blobdata> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Blobdatas matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Blobdatas.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Blobdata> findAll(String query, Pageable pageable);

    /**
	 * Exports all Blobdatas matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Blobdatas in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Blobdata.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

